FORMAT: 1A

# Prueba  de conocimiento/BWC

API que nos permite mostrar las condiciones climáticas para una ciudad
específica.
# Group Servicios de BWC

## Servicios de mapa [/map-box]

Servicios que nos permiten interactuar con los servicios de mapbox

### Coordenadas de una ciudad [GET /map-box/{ciudad}]

Servicio el cual permite obtener las coordendas de una ciduad

+ Parameters
    + ciudad - el nombre de una ciudad.

+ Response 200 (application/json)

        {
            "type": "FeatureCollection",
            "query": [
                "armenia"
            ],
            "features": [
                {
                    "id": "country.9516906854837430",
                    "type": "Feature",
                    "place_type": [
                        "country"
                    ],
                    "relevance": 1,
                    "properties": {
                        "short_code": "am",
                        "wikidata": "Q399"
                    },
                    "text": "Armenia",
                    "place_name": "Armenia",
                    "bbox": [
                        43.4482790013412,
                        38.8402730038063,
                        46.6329549648301,
                        41.2998729999239
                    ],
                    "center": [
                        44.6603948347298,
                        40.6056564938472
                    ],
                    "geometry": {
                        "type": "Point",
                        "coordinates": [
                            44.6603948347298,
                            40.6056564938472
                        ]
                    }
                },
                {
                    "id": "place.15102983687837430",
                    "type": "Feature",
                    "place_type": [
                        "place"
                    ],
                    "relevance": 1,
                    "properties": {
                        "wikidata": "Q328518"
                    },
                    "text": "Armenia",
                    "place_name": "Armenia, Quindío, Colombia",
                    "bbox": [
                        -75.787704,
                        4.395269,
                        -75.63324,
                        4.588419
                    ],
                    "center": [
                        -75.6725,
                        4.53889
                    ],
                    "geometry": {
                        "type": "Point",
                        "coordinates": [
                            -75.6725,
                            4.53889
                        ]
                    },
                    "context": [
                        {
                            "id": "region.9942195783434000",
                            "short_code": "CO-QUI",
                            "wikidata": "Q13995",
                            "text": "Quindío"
                        },
                        {
                            "id": "country.12227578366646840",
                            "short_code": "co",
                            "wikidata": "Q739",
                            "text": "Colombia"
                        }
                    ]
                },
                {
                    "id": "place.9270021222837430",
                    "type": "Feature",
                    "place_type": [
                        "place"
                    ],
                    "relevance": 1,
                    "properties": [],
                    "text": "Armenia",
                    "place_name": "Armenia, Sonsonate, El Salvador",
                    "bbox": [
                        -89.546555,
                        13.707391,
                        -89.446145,
                        13.813832
                    ],
                    "center": [
                        -89.4989,
                        13.7436
                    ],
                    "geometry": {
                        "type": "Point",
                        "coordinates": [
                            -89.4989,
                            13.7436
                        ]
                    },
                    "context": [
                        {
                            "id": "region.12982874330059550",
                            "short_code": "SV-SO",
                            "wikidata": "Q212540",
                            "text": "Sonsonate"
                        },
                        {
                            "id": "country.8557697608768610",
                            "short_code": "sv",
                            "wikidata": "Q792",
                            "text": "El Salvador"
                        }
                    ]
                },
                {
                    "id": "poi.670014964297",
                    "type": "Feature",
                    "place_type": [
                        "poi"
                    ],
                    "relevance": 1,
                    "properties": {
                        "foursquare": "4bdcfcb3d2e70f47287f0001",
                        "landmark": true,
                        "address": "60 Hill St",
                        "category": "religious, religion",
                        "maki": "place-of-worship"
                    },
                    "text": "Armenian Church of St Gregory the Illuminator",
                    "place_name": "Armenian Church of St Gregory the Illuminator, 60 Hill St, Singapore, Central 179366, Singapore",
                    "center": [
                        103.849498,
                        1.293109
                    ],
                    "geometry": {
                        "coordinates": [
                            103.849498,
                            1.293109
                        ],
                        "type": "Point"
                    },
                    "context": [
                        {
                            "id": "postcode.12536290676892540",
                            "text": "179366"
                        },
                        {
                            "id": "place.8529875252536600",
                            "wikidata": "Q334",
                            "text": "Singapore"
                        },
                        {
                            "id": "region.10000694609761180",
                            "short_code": "SG-01",
                            "wikidata": "Q2091778",
                            "text": "Central"
                        },
                        {
                            "id": "country.6538037389536600",
                            "short_code": "sg",
                            "wikidata": "Q334",
                            "text": "Singapore"
                        }
                    ]
                },
                {
                    "id": "poi.206158476090",
                    "type": "Feature",
                    "place_type": [
                        "poi"
                    ],
                    "relevance": 1,
                    "properties": {
                        "foursquare": "4cd58845ab19a093afc63feb",
                        "landmark": true,
                        "address": "Dzirnavu iela 62",
                        "category": "caucasian restaurant, caucasian food, restaurant"
                    },
                    "text": "Armenia",
                    "place_name": "Armenia, Dzirnavu iela 62, Riga Latvia",
                    "center": [
                        24.120418,
                        56.954312
                    ],
                    "geometry": {
                        "coordinates": [
                            24.120418,
                            56.954312
                        ],
                        "type": "Point"
                    },
                    "context": [
                        {
                            "id": "place.7084703387395980",
                            "short_code": "LV-RIX",
                            "wikidata": "Q1773",
                            "text": "Riga"
                        },
                        {
                            "id": "country.10112690060267300",
                            "short_code": "lv",
                            "wikidata": "Q211",
                            "text": "Latvia"
                        }
                    ]
                }
            ],
            "attribution": "NOTICE: © 2020 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained. POI(s) provided by Foursquare."
        }

## Clima [/weather]

Servicios que nos permiten interactuar con los servicios de darksky

### Clima de una ciudad mediante coordenadas [GET /weather/{lat}/{long}]

Servicio que nos permite obtener la informacion del clima mediante 
la coordenadas latitud y longitud.

+ Parameters
    + lat - coordenada de latitud de una ciudad.
    + long - coordenada de longitud de una ciudad.

+ Response 200 (application/json)

        {
            "latitude": 4.55,
            "longitude": 34.55,
            "timezone": "Africa/Juba",
            "currently": {
                "time": 1600221238,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 76.35,
                "apparentTemperature": 76.61,
                "dewPoint": 62.49,
                "humidity": 0.62,
                "pressure": 1009.7,
                "windSpeed": 5.76,
                "windGust": 14.8,
                "windBearing": 220,
                "cloudCover": 0.6,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 269.1
            },
            "hourly": {
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "data": [
                    {
                        "time": 1600218000,
                        "summary": "Partly Cloudy",
                        "icon": "partly-cloudy-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 77.42,
                        "apparentTemperature": 77.73,
                        "dewPoint": 62.9,
                        "humidity": 0.61,
                        "pressure": 1009.2,
                        "windSpeed": 5.05,
                        "windGust": 11.87,
                        "windBearing": 243,
                        "cloudCover": 0.44,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 269.4
                    },
                    {
                        "time": 1600221600,
                        "summary": "Mostly Cloudy",
                        "icon": "partly-cloudy-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 76.28,
                        "apparentTemperature": 76.53,
                        "dewPoint": 62.44,
                        "humidity": 0.62,
                        "pressure": 1009.8,
                        "windSpeed": 5.84,
                        "windGust": 15.11,
                        "windBearing": 218,
                        "cloudCover": 0.62,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 269.1
                    },
                    {
                        "time": 1600225200,
                        "summary": "Mostly Cloudy",
                        "icon": "partly-cloudy-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 76.18,
                        "apparentTemperature": 76.39,
                        "dewPoint": 61.99,
                        "humidity": 0.62,
                        "pressure": 1010.4,
                        "windSpeed": 6.75,
                        "windGust": 17.97,
                        "windBearing": 200,
                        "cloudCover": 0.73,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 269
                    },
                    {
                        "time": 1600228800,
                        "summary": "Mostly Cloudy",
                        "icon": "partly-cloudy-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 77.83,
                        "apparentTemperature": 78.04,
                        "dewPoint": 61.91,
                        "humidity": 0.58,
                        "pressure": 1011.4,
                        "windSpeed": 8,
                        "windGust": 20.46,
                        "windBearing": 180,
                        "cloudCover": 0.75,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 269.6
                    },
                    {
                        "time": 1600232400,
                        "summary": "Mostly Cloudy",
                        "icon": "partly-cloudy-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 80.58,
                        "apparentTemperature": 81.92,
                        "dewPoint": 63.01,
                        "humidity": 0.55,
                        "pressure": 1012.6,
                        "windSpeed": 9.95,
                        "windGust": 22.58,
                        "windBearing": 151,
                        "cloudCover": 0.71,
                        "uvIndex": 1,
                        "visibility": 10,
                        "ozone": 270.5
                    },
                    {
                        "time": 1600236000,
                        "summary": "Mostly Cloudy",
                        "icon": "partly-cloudy-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 83.09,
                        "apparentTemperature": 84.12,
                        "dewPoint": 62.87,
                        "humidity": 0.51,
                        "pressure": 1012.9,
                        "windSpeed": 11.78,
                        "windGust": 23.45,
                        "windBearing": 131,
                        "cloudCover": 0.62,
                        "uvIndex": 3,
                        "visibility": 10,
                        "ozone": 271.2
                    },
                    {
                        "time": 1600239600,
                        "summary": "Partly Cloudy",
                        "icon": "partly-cloudy-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 85.8,
                        "apparentTemperature": 86.26,
                        "dewPoint": 61.89,
                        "humidity": 0.45,
                        "pressure": 1012.7,
                        "windSpeed": 12.48,
                        "windGust": 22.39,
                        "windBearing": 124,
                        "cloudCover": 0.44,
                        "uvIndex": 6,
                        "visibility": 10,
                        "ozone": 271.1
                    },
                    {
                        "time": 1600243200,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0.0002,
                        "precipProbability": 0.01,
                        "precipType": "rain",
                        "temperature": 89.35,
                        "apparentTemperature": 89.61,
                        "dewPoint": 61.57,
                        "humidity": 0.4,
                        "pressure": 1011.6,
                        "windSpeed": 12.67,
                        "windGust": 20.11,
                        "windBearing": 122,
                        "cloudCover": 0.2,
                        "uvIndex": 10,
                        "visibility": 10,
                        "ozone": 270.9
                    },
                    {
                        "time": 1600246800,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0.0003,
                        "precipProbability": 0.01,
                        "precipType": "rain",
                        "temperature": 92.43,
                        "apparentTemperature": 92.49,
                        "dewPoint": 60.78,
                        "humidity": 0.35,
                        "pressure": 1010.5,
                        "windSpeed": 12.66,
                        "windGust": 17.83,
                        "windBearing": 120,
                        "cloudCover": 0.03,
                        "uvIndex": 13,
                        "visibility": 10,
                        "ozone": 270.4
                    },
                    {
                        "time": 1600250400,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0.0002,
                        "precipProbability": 0.01,
                        "precipType": "rain",
                        "temperature": 94.47,
                        "apparentTemperature": 94.47,
                        "dewPoint": 59.12,
                        "humidity": 0.31,
                        "pressure": 1009.1,
                        "windSpeed": 11.87,
                        "windGust": 15.93,
                        "windBearing": 120,
                        "cloudCover": 0,
                        "uvIndex": 13,
                        "visibility": 10,
                        "ozone": 270
                    },
                    {
                        "time": 1600254000,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 95.54,
                        "apparentTemperature": 95.54,
                        "dewPoint": 57.45,
                        "humidity": 0.28,
                        "pressure": 1007.4,
                        "windSpeed": 10.49,
                        "windGust": 14.03,
                        "windBearing": 121,
                        "cloudCover": 0,
                        "uvIndex": 11,
                        "visibility": 10,
                        "ozone": 269.3
                    },
                    {
                        "time": 1600257600,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 95.96,
                        "apparentTemperature": 95.96,
                        "dewPoint": 55.61,
                        "humidity": 0.26,
                        "pressure": 1006.2,
                        "windSpeed": 9.41,
                        "windGust": 12.45,
                        "windBearing": 122,
                        "cloudCover": 0.01,
                        "uvIndex": 8,
                        "visibility": 10,
                        "ozone": 269
                    },
                    {
                        "time": 1600261200,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 96.6,
                        "apparentTemperature": 96.6,
                        "dewPoint": 54.92,
                        "humidity": 0.25,
                        "pressure": 1005.4,
                        "windSpeed": 8.96,
                        "windGust": 11,
                        "windBearing": 120,
                        "cloudCover": 0.01,
                        "uvIndex": 5,
                        "visibility": 10,
                        "ozone": 269.2
                    },
                    {
                        "time": 1600264800,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 96.93,
                        "apparentTemperature": 96.93,
                        "dewPoint": 54.06,
                        "humidity": 0.24,
                        "pressure": 1004.9,
                        "windSpeed": 8.8,
                        "windGust": 9.87,
                        "windBearing": 117,
                        "cloudCover": 0,
                        "uvIndex": 2,
                        "visibility": 10,
                        "ozone": 269.5
                    },
                    {
                        "time": 1600268400,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 96.56,
                        "apparentTemperature": 96.56,
                        "dewPoint": 53.94,
                        "humidity": 0.24,
                        "pressure": 1004.9,
                        "windSpeed": 8.65,
                        "windGust": 9.68,
                        "windBearing": 116,
                        "cloudCover": 0,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 270
                    },
                    {
                        "time": 1600272000,
                        "summary": "Clear",
                        "icon": "clear-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 94.55,
                        "apparentTemperature": 94.55,
                        "dewPoint": 53.83,
                        "humidity": 0.25,
                        "pressure": 1005.6,
                        "windSpeed": 8.47,
                        "windGust": 11.63,
                        "windBearing": 115,
                        "cloudCover": 0,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 270.8
                    },
                    {
                        "time": 1600275600,
                        "summary": "Clear",
                        "icon": "clear-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 91.46,
                        "apparentTemperature": 91.46,
                        "dewPoint": 54.37,
                        "humidity": 0.29,
                        "pressure": 1006.2,
                        "windSpeed": 8.26,
                        "windGust": 14.57,
                        "windBearing": 116,
                        "cloudCover": 0,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 271.8
                    },
                    {
                        "time": 1600279200,
                        "summary": "Clear",
                        "icon": "clear-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 89.03,
                        "apparentTemperature": 89.03,
                        "dewPoint": 55.02,
                        "humidity": 0.32,
                        "pressure": 1006.9,
                        "windSpeed": 7.85,
                        "windGust": 15.64,
                        "windBearing": 118,
                        "cloudCover": 0.05,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 272.5
                    },
                    {
                        "time": 1600282800,
                        "summary": "Clear",
                        "icon": "clear-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 87.56,
                        "apparentTemperature": 87.56,
                        "dewPoint": 55.41,
                        "humidity": 0.34,
                        "pressure": 1007.8,
                        "windSpeed": 6.93,
                        "windGust": 12.57,
                        "windBearing": 128,
                        "cloudCover": 0.25,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 272.4
                    },
                    {
                        "time": 1600286400,
                        "summary": "Partly Cloudy",
                        "icon": "partly-cloudy-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 86.32,
                        "apparentTemperature": 86.32,
                        "dewPoint": 55.91,
                        "humidity": 0.36,
                        "pressure": 1008,
                        "windSpeed": 5.82,
                        "windGust": 7.65,
                        "windBearing": 141,
                        "cloudCover": 0.51,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 271.8
                    },
                    {
                        "time": 1600290000,
                        "summary": "Mostly Cloudy",
                        "icon": "partly-cloudy-night",
                        "precipIntensity": 0.0004,
                        "precipProbability": 0.03,
                        "precipType": "rain",
                        "temperature": 84.85,
                        "apparentTemperature": 84.85,
                        "dewPoint": 56.58,
                        "humidity": 0.38,
                        "pressure": 1008.3,
                        "windSpeed": 5.12,
                        "windGust": 5.39,
                        "windBearing": 143,
                        "cloudCover": 0.72,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 271.4
                    },
                    {
                        "time": 1600293600,
                        "summary": "Mostly Cloudy",
                        "icon": "partly-cloudy-night",
                        "precipIntensity": 0.0004,
                        "precipProbability": 0.03,
                        "precipType": "rain",
                        "temperature": 82.77,
                        "apparentTemperature": 82.77,
                        "dewPoint": 57.95,
                        "humidity": 0.43,
                        "pressure": 1008.2,
                        "windSpeed": 5.34,
                        "windGust": 6.14,
                        "windBearing": 120,
                        "cloudCover": 0.79,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 271.4
                    },
                    {
                        "time": 1600297200,
                        "summary": "Mostly Cloudy",
                        "icon": "partly-cloudy-night",
                        "precipIntensity": 0.0004,
                        "precipProbability": 0.03,
                        "precipType": "rain",
                        "temperature": 81.16,
                        "apparentTemperature": 81.8,
                        "dewPoint": 60.33,
                        "humidity": 0.49,
                        "pressure": 1007.9,
                        "windSpeed": 6,
                        "windGust": 9.59,
                        "windBearing": 98,
                        "cloudCover": 0.8,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 271.5
                    },
                    {
                        "time": 1600300800,
                        "summary": "Mostly Cloudy",
                        "icon": "partly-cloudy-night",
                        "precipIntensity": 0.0003,
                        "precipProbability": 0.03,
                        "precipType": "rain",
                        "temperature": 79.81,
                        "apparentTemperature": 81.03,
                        "dewPoint": 61.85,
                        "humidity": 0.54,
                        "pressure": 1007.8,
                        "windSpeed": 6.36,
                        "windGust": 12.47,
                        "windBearing": 135,
                        "cloudCover": 0.8,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 271.4
                    },
                    {
                        "time": 1600304400,
                        "summary": "Mostly Cloudy",
                        "icon": "partly-cloudy-night",
                        "precipIntensity": 0.0003,
                        "precipProbability": 0.03,
                        "precipType": "rain",
                        "temperature": 78.26,
                        "apparentTemperature": 78.49,
                        "dewPoint": 62.01,
                        "humidity": 0.57,
                        "pressure": 1008.3,
                        "windSpeed": 5.82,
                        "windGust": 13.58,
                        "windBearing": 98,
                        "cloudCover": 0.82,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 270.6
                    },
                    {
                        "time": 1600308000,
                        "summary": "Mostly Cloudy",
                        "icon": "partly-cloudy-night",
                        "precipIntensity": 0.0008,
                        "precipProbability": 0.02,
                        "precipType": "rain",
                        "temperature": 77.17,
                        "apparentTemperature": 77.38,
                        "dewPoint": 61.94,
                        "humidity": 0.59,
                        "pressure": 1009,
                        "windSpeed": 5.04,
                        "windGust": 14.12,
                        "windBearing": 117,
                        "cloudCover": 0.82,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 269.6
                    },
                    {
                        "time": 1600311600,
                        "summary": "Mostly Cloudy",
                        "icon": "partly-cloudy-night",
                        "precipIntensity": 0.0013,
                        "precipProbability": 0.02,
                        "precipType": "rain",
                        "temperature": 77,
                        "apparentTemperature": 77.18,
                        "dewPoint": 61.64,
                        "humidity": 0.59,
                        "pressure": 1009.9,
                        "windSpeed": 5.15,
                        "windGust": 15.11,
                        "windBearing": 138,
                        "cloudCover": 0.79,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 268.8
                    },
                    {
                        "time": 1600315200,
                        "summary": "Mostly Cloudy",
                        "icon": "partly-cloudy-day",
                        "precipIntensity": 0.0008,
                        "precipProbability": 0.01,
                        "precipType": "rain",
                        "temperature": 78.47,
                        "apparentTemperature": 78.69,
                        "dewPoint": 61.84,
                        "humidity": 0.57,
                        "pressure": 1010.7,
                        "windSpeed": 7.14,
                        "windGust": 17.39,
                        "windBearing": 140,
                        "cloudCover": 0.68,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 268.8
                    },
                    {
                        "time": 1600318800,
                        "summary": "Partly Cloudy",
                        "icon": "partly-cloudy-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 81.34,
                        "apparentTemperature": 82.57,
                        "dewPoint": 62.95,
                        "humidity": 0.54,
                        "pressure": 1011.8,
                        "windSpeed": 10.44,
                        "windGust": 20.15,
                        "windBearing": 133,
                        "cloudCover": 0.54,
                        "uvIndex": 1,
                        "visibility": 10,
                        "ozone": 269
                    },
                    {
                        "time": 1600322400,
                        "summary": "Partly Cloudy",
                        "icon": "partly-cloudy-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 83.86,
                        "apparentTemperature": 84.7,
                        "dewPoint": 62.54,
                        "humidity": 0.49,
                        "pressure": 1012.3,
                        "windSpeed": 13.36,
                        "windGust": 21.76,
                        "windBearing": 126,
                        "cloudCover": 0.39,
                        "uvIndex": 3,
                        "visibility": 10,
                        "ozone": 268.8
                    },
                    {
                        "time": 1600326000,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 86.72,
                        "apparentTemperature": 87.14,
                        "dewPoint": 61.9,
                        "humidity": 0.44,
                        "pressure": 1012,
                        "windSpeed": 14.57,
                        "windGust": 21.32,
                        "windBearing": 125,
                        "cloudCover": 0.25,
                        "uvIndex": 7,
                        "visibility": 10,
                        "ozone": 268
                    },
                    {
                        "time": 1600329600,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 90.35,
                        "apparentTemperature": 90.9,
                        "dewPoint": 62.13,
                        "humidity": 0.39,
                        "pressure": 1011.1,
                        "windSpeed": 14.95,
                        "windGust": 19.73,
                        "windBearing": 125,
                        "cloudCover": 0.1,
                        "uvIndex": 10,
                        "visibility": 10,
                        "ozone": 266.8
                    },
                    {
                        "time": 1600333200,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 93.65,
                        "apparentTemperature": 93.98,
                        "dewPoint": 61.12,
                        "humidity": 0.34,
                        "pressure": 1010.2,
                        "windSpeed": 15.06,
                        "windGust": 18.33,
                        "windBearing": 124,
                        "cloudCover": 0,
                        "uvIndex": 13,
                        "visibility": 10,
                        "ozone": 266.2
                    },
                    {
                        "time": 1600336800,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 96.02,
                        "apparentTemperature": 96.02,
                        "dewPoint": 58.96,
                        "humidity": 0.29,
                        "pressure": 1008.9,
                        "windSpeed": 14.7,
                        "windGust": 17.63,
                        "windBearing": 124,
                        "cloudCover": 0,
                        "uvIndex": 13,
                        "visibility": 10,
                        "ozone": 266.2
                    },
                    {
                        "time": 1600340400,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 97.6,
                        "apparentTemperature": 97.6,
                        "dewPoint": 56.59,
                        "humidity": 0.26,
                        "pressure": 1007.4,
                        "windSpeed": 13.84,
                        "windGust": 17.1,
                        "windBearing": 123,
                        "cloudCover": 0,
                        "uvIndex": 12,
                        "visibility": 10,
                        "ozone": 266.7
                    },
                    {
                        "time": 1600344000,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 98.28,
                        "apparentTemperature": 98.28,
                        "dewPoint": 54.28,
                        "humidity": 0.23,
                        "pressure": 1006.1,
                        "windSpeed": 13.12,
                        "windGust": 16.66,
                        "windBearing": 122,
                        "cloudCover": 0,
                        "uvIndex": 8,
                        "visibility": 10,
                        "ozone": 266.9
                    },
                    {
                        "time": 1600347600,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 98.83,
                        "apparentTemperature": 98.83,
                        "dewPoint": 52.36,
                        "humidity": 0.21,
                        "pressure": 1005.3,
                        "windSpeed": 12.85,
                        "windGust": 16.18,
                        "windBearing": 121,
                        "cloudCover": 0,
                        "uvIndex": 5,
                        "visibility": 10,
                        "ozone": 266.2
                    },
                    {
                        "time": 1600351200,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 98.69,
                        "apparentTemperature": 98.69,
                        "dewPoint": 51.02,
                        "humidity": 0.2,
                        "pressure": 1005,
                        "windSpeed": 12.71,
                        "windGust": 15.79,
                        "windBearing": 119,
                        "cloudCover": 0,
                        "uvIndex": 2,
                        "visibility": 10,
                        "ozone": 265.4
                    },
                    {
                        "time": 1600354800,
                        "summary": "Clear",
                        "icon": "clear-day",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 97.83,
                        "apparentTemperature": 97.83,
                        "dewPoint": 50.64,
                        "humidity": 0.2,
                        "pressure": 1005,
                        "windSpeed": 12.51,
                        "windGust": 15.66,
                        "windBearing": 120,
                        "cloudCover": 0,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 265.1
                    },
                    {
                        "time": 1600358400,
                        "summary": "Clear",
                        "icon": "clear-night",
                        "precipIntensity": 0.0002,
                        "precipProbability": 0.01,
                        "precipType": "rain",
                        "temperature": 95.09,
                        "apparentTemperature": 95.09,
                        "dewPoint": 51.17,
                        "humidity": 0.23,
                        "pressure": 1005.9,
                        "windSpeed": 12.17,
                        "windGust": 15.85,
                        "windBearing": 122,
                        "cloudCover": 0,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 265.7
                    },
                    {
                        "time": 1600362000,
                        "summary": "Clear",
                        "icon": "clear-night",
                        "precipIntensity": 0.0003,
                        "precipProbability": 0.01,
                        "precipType": "rain",
                        "temperature": 92.34,
                        "apparentTemperature": 92.34,
                        "dewPoint": 52.45,
                        "humidity": 0.26,
                        "pressure": 1006.9,
                        "windSpeed": 11.66,
                        "windGust": 16.29,
                        "windBearing": 127,
                        "cloudCover": 0,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 266.9
                    },
                    {
                        "time": 1600365600,
                        "summary": "Clear",
                        "icon": "clear-night",
                        "precipIntensity": 0.0003,
                        "precipProbability": 0.01,
                        "precipType": "rain",
                        "temperature": 89.93,
                        "apparentTemperature": 89.93,
                        "dewPoint": 53.75,
                        "humidity": 0.29,
                        "pressure": 1008,
                        "windSpeed": 11.1,
                        "windGust": 17.01,
                        "windBearing": 132,
                        "cloudCover": 0,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 268.1
                    },
                    {
                        "time": 1600369200,
                        "summary": "Clear",
                        "icon": "clear-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 88.41,
                        "apparentTemperature": 88.41,
                        "dewPoint": 55.03,
                        "humidity": 0.32,
                        "pressure": 1008.6,
                        "windSpeed": 10.54,
                        "windGust": 17.87,
                        "windBearing": 134,
                        "cloudCover": 0,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 269.2
                    },
                    {
                        "time": 1600372800,
                        "summary": "Clear",
                        "icon": "clear-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 87.16,
                        "apparentTemperature": 87.16,
                        "dewPoint": 56.83,
                        "humidity": 0.36,
                        "pressure": 1008.5,
                        "windSpeed": 10.04,
                        "windGust": 19.02,
                        "windBearing": 135,
                        "cloudCover": 0,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 270
                    },
                    {
                        "time": 1600376400,
                        "summary": "Clear",
                        "icon": "clear-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 85.81,
                        "apparentTemperature": 85.81,
                        "dewPoint": 58.51,
                        "humidity": 0.4,
                        "pressure": 1008.1,
                        "windSpeed": 9.89,
                        "windGust": 20.82,
                        "windBearing": 136,
                        "cloudCover": 0,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 270.5
                    },
                    {
                        "time": 1600380000,
                        "summary": "Clear",
                        "icon": "clear-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 84.04,
                        "apparentTemperature": 84.06,
                        "dewPoint": 60,
                        "humidity": 0.44,
                        "pressure": 1008,
                        "windSpeed": 10.48,
                        "windGust": 24.06,
                        "windBearing": 135,
                        "cloudCover": 0,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 270.2
                    },
                    {
                        "time": 1600383600,
                        "summary": "Clear",
                        "icon": "clear-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 82.36,
                        "apparentTemperature": 83.06,
                        "dewPoint": 61.47,
                        "humidity": 0.49,
                        "pressure": 1007.7,
                        "windSpeed": 11.58,
                        "windGust": 27.96,
                        "windBearing": 134,
                        "cloudCover": 0,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 269.2
                    },
                    {
                        "time": 1600387200,
                        "summary": "Clear",
                        "icon": "clear-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 80.95,
                        "apparentTemperature": 82.02,
                        "dewPoint": 62.07,
                        "humidity": 0.53,
                        "pressure": 1007.7,
                        "windSpeed": 12.38,
                        "windGust": 30.52,
                        "windBearing": 134,
                        "cloudCover": 0,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 268.5
                    },
                    {
                        "time": 1600390800,
                        "summary": "Clear",
                        "icon": "clear-night",
                        "precipIntensity": 0,
                        "precipProbability": 0,
                        "temperature": 79.17,
                        "apparentTemperature": 79.43,
                        "dewPoint": 62.28,
                        "humidity": 0.56,
                        "pressure": 1008.7,
                        "windSpeed": 12.16,
                        "windGust": 30.65,
                        "windBearing": 134,
                        "cloudCover": 0,
                        "uvIndex": 0,
                        "visibility": 10,
                        "ozone": 267.8
                    }
                ]
            },
            "daily": {
                "summary": "Rain next Wednesday.",
                "icon": "rain",
                "data": [
                    {
                        "time": 1600203600,
                        "summary": "Clear throughout the day.",
                        "icon": "clear-day",
                        "sunriseTime": 1600227240,
                        "sunsetTime": 1600270920,
                        "moonPhase": 0.97,
                        "precipIntensity": 0.0001,
                        "precipIntensityMax": 0.0006,
                        "precipIntensityMaxTime": 1600203600,
                        "precipProbability": 0.1,
                        "precipType": "rain",
                        "temperatureHigh": 97.43,
                        "temperatureHighTime": 1600264740,
                        "temperatureLow": 76.41,
                        "temperatureLowTime": 1600310400,
                        "apparentTemperatureHigh": 96.93,
                        "apparentTemperatureHighTime": 1600264740,
                        "apparentTemperatureLow": 77.09,
                        "apparentTemperatureLowTime": 1600310520,
                        "dewPoint": 58.98,
                        "humidity": 0.41,
                        "pressure": 1008.7,
                        "windSpeed": 8.34,
                        "windGust": 23.46,
                        "windGustTime": 1600235880,
                        "windBearing": 134,
                        "cloudCover": 0.27,
                        "uvIndex": 13,
                        "uvIndexTime": 1600249200,
                        "visibility": 10,
                        "ozone": 270.4,
                        "temperatureMin": 75.55,
                        "temperatureMinTime": 1600223820,
                        "temperatureMax": 97.43,
                        "temperatureMaxTime": 1600264740,
                        "apparentTemperatureMin": 76.27,
                        "apparentTemperatureMinTime": 1600223940,
                        "apparentTemperatureMax": 96.93,
                        "apparentTemperatureMaxTime": 1600264740
                    },
                    {
                        "time": 1600290000,
                        "summary": "Clear throughout the day.",
                        "icon": "clear-day",
                        "sunriseTime": 1600313640,
                        "sunsetTime": 1600357320,
                        "moonPhase": 0.01,
                        "precipIntensity": 0.0003,
                        "precipIntensityMax": 0.0013,
                        "precipIntensityMaxTime": 1600311600,
                        "precipProbability": 0.1,
                        "precipType": "rain",
                        "temperatureHigh": 99.37,
                        "temperatureHighTime": 1600348680,
                        "temperatureLow": 76.96,
                        "temperatureLowTime": 1600397700,
                        "apparentTemperatureHigh": 98.87,
                        "apparentTemperatureHighTime": 1600348680,
                        "apparentTemperatureLow": 77.7,
                        "apparentTemperatureLowTime": 1600397700,
                        "dewPoint": 57.87,
                        "humidity": 0.38,
                        "pressure": 1008.5,
                        "windSpeed": 10.5,
                        "windGust": 21.83,
                        "windGustTime": 1600323180,
                        "windBearing": 125,
                        "cloudCover": 0.3,
                        "uvIndex": 14,
                        "uvIndexTime": 1600335240,
                        "visibility": 10,
                        "ozone": 268.3,
                        "temperatureMin": 76.41,
                        "temperatureMinTime": 1600310400,
                        "temperatureMax": 99.37,
                        "temperatureMaxTime": 1600348680,
                        "apparentTemperatureMin": 77.09,
                        "apparentTemperatureMinTime": 1600310520,
                        "apparentTemperatureMax": 98.87,
                        "apparentTemperatureMaxTime": 1600348680
                    },
                    {
                        "time": 1600376400,
                        "summary": "Clear throughout the day.",
                        "icon": "clear-day",
                        "sunriseTime": 1600399980,
                        "sunsetTime": 1600443660,
                        "moonPhase": 0.05,
                        "precipIntensity": 0.0001,
                        "precipIntensityMax": 0.0003,
                        "precipIntensityMaxTime": 1600398240,
                        "precipProbability": 0.04,
                        "precipType": "rain",
                        "temperatureHigh": 97.89,
                        "temperatureHighTime": 1600431180,
                        "temperatureLow": 75.83,
                        "temperatureLowTime": 1600484160,
                        "apparentTemperatureHigh": 97.39,
                        "apparentTemperatureHighTime": 1600431180,
                        "apparentTemperatureLow": 76.69,
                        "apparentTemperatureLowTime": 1600484100,
                        "dewPoint": 58.28,
                        "humidity": 0.39,
                        "pressure": 1008.6,
                        "windSpeed": 13.3,
                        "windGust": 30.82,
                        "windGustTime": 1600389000,
                        "windBearing": 126,
                        "cloudCover": 0,
                        "uvIndex": 14,
                        "uvIndexTime": 1600421820,
                        "visibility": 10,
                        "ozone": 267.8,
                        "temperatureMin": 76.96,
                        "temperatureMinTime": 1600397700,
                        "temperatureMax": 97.89,
                        "temperatureMaxTime": 1600431180,
                        "apparentTemperatureMin": 77.7,
                        "apparentTemperatureMinTime": 1600397700,
                        "apparentTemperatureMax": 97.39,
                        "apparentTemperatureMaxTime": 1600431180
                    },
                    {
                        "time": 1600462800,
                        "summary": "Clear throughout the day.",
                        "icon": "clear-day",
                        "sunriseTime": 1600486380,
                        "sunsetTime": 1600530060,
                        "moonPhase": 0.09,
                        "precipIntensity": 0.0001,
                        "precipIntensityMax": 0.0003,
                        "precipIntensityMaxTime": 1600475580,
                        "precipProbability": 0.02,
                        "precipType": "rain",
                        "temperatureHigh": 98.32,
                        "temperatureHighTime": 1600521240,
                        "temperatureLow": 75.89,
                        "temperatureLowTime": 1600570080,
                        "apparentTemperatureHigh": 97.82,
                        "apparentTemperatureHighTime": 1600521240,
                        "apparentTemperatureLow": 76.64,
                        "apparentTemperatureLowTime": 1600570080,
                        "dewPoint": 57.63,
                        "humidity": 0.39,
                        "pressure": 1008,
                        "windSpeed": 12.18,
                        "windGust": 28.78,
                        "windGustTime": 1600476480,
                        "windBearing": 127,
                        "cloudCover": 0.03,
                        "uvIndex": 13,
                        "uvIndexTime": 1600508220,
                        "visibility": 10,
                        "ozone": 271.5,
                        "temperatureMin": 75.83,
                        "temperatureMinTime": 1600484160,
                        "temperatureMax": 98.32,
                        "temperatureMaxTime": 1600521240,
                        "apparentTemperatureMin": 76.69,
                        "apparentTemperatureMinTime": 1600484100,
                        "apparentTemperatureMax": 97.82,
                        "apparentTemperatureMaxTime": 1600521240
                    },
                    {
                        "time": 1600549200,
                        "summary": "Clear throughout the day.",
                        "icon": "clear-day",
                        "sunriseTime": 1600572780,
                        "sunsetTime": 1600616400,
                        "moonPhase": 0.13,
                        "precipIntensity": 0.0001,
                        "precipIntensityMax": 0.0003,
                        "precipIntensityMaxTime": 1600623180,
                        "precipProbability": 0.09,
                        "precipType": "rain",
                        "temperatureHigh": 97.68,
                        "temperatureHighTime": 1600603980,
                        "temperatureLow": 75.95,
                        "temperatureLowTime": 1600657200,
                        "apparentTemperatureHigh": 97.18,
                        "apparentTemperatureHighTime": 1600603980,
                        "apparentTemperatureLow": 76.68,
                        "apparentTemperatureLowTime": 1600657200,
                        "dewPoint": 58.13,
                        "humidity": 0.4,
                        "pressure": 1008.3,
                        "windSpeed": 12.12,
                        "windGust": 26.45,
                        "windGustTime": 1600561740,
                        "windBearing": 125,
                        "cloudCover": 0.24,
                        "uvIndex": 9,
                        "uvIndexTime": 1600594680,
                        "visibility": 10,
                        "ozone": 269.3,
                        "temperatureMin": 75.89,
                        "temperatureMinTime": 1600570080,
                        "temperatureMax": 97.68,
                        "temperatureMaxTime": 1600603980,
                        "apparentTemperatureMin": 76.64,
                        "apparentTemperatureMinTime": 1600570080,
                        "apparentTemperatureMax": 97.18,
                        "apparentTemperatureMaxTime": 1600603980
                    },
                    {
                        "time": 1600635600,
                        "summary": "Clear throughout the day.",
                        "icon": "clear-day",
                        "sunriseTime": 1600659180,
                        "sunsetTime": 1600702800,
                        "moonPhase": 0.17,
                        "precipIntensity": 0.0001,
                        "precipIntensityMax": 0.0002,
                        "precipIntensityMaxTime": 1600711860,
                        "precipProbability": 0.05,
                        "precipType": "rain",
                        "temperatureHigh": 97.78,
                        "temperatureHighTime": 1600696080,
                        "temperatureLow": 75.56,
                        "temperatureLowTime": 1600743240,
                        "apparentTemperatureHigh": 97.28,
                        "apparentTemperatureHighTime": 1600696080,
                        "apparentTemperatureLow": 76.28,
                        "apparentTemperatureLowTime": 1600743240,
                        "dewPoint": 58.04,
                        "humidity": 0.4,
                        "pressure": 1009.2,
                        "windSpeed": 8.94,
                        "windGust": 21.86,
                        "windGustTime": 1600668780,
                        "windBearing": 122,
                        "cloudCover": 0.13,
                        "uvIndex": 13,
                        "uvIndexTime": 1600680780,
                        "visibility": 10,
                        "ozone": 270.2,
                        "temperatureMin": 75.95,
                        "temperatureMinTime": 1600657200,
                        "temperatureMax": 97.78,
                        "temperatureMaxTime": 1600696080,
                        "apparentTemperatureMin": 76.68,
                        "apparentTemperatureMinTime": 1600657200,
                        "apparentTemperatureMax": 97.28,
                        "apparentTemperatureMaxTime": 1600696080
                    },
                    {
                        "time": 1600722000,
                        "summary": "Clear throughout the day.",
                        "icon": "clear-day",
                        "sunriseTime": 1600745520,
                        "sunsetTime": 1600789140,
                        "moonPhase": 0.2,
                        "precipIntensity": 0.0002,
                        "precipIntensityMax": 0.0014,
                        "precipIntensityMaxTime": 1600743300,
                        "precipProbability": 0.07,
                        "precipType": "rain",
                        "temperatureHigh": 98.35,
                        "temperatureHighTime": 1600781100,
                        "temperatureLow": 75.94,
                        "temperatureLowTime": 1600827900,
                        "apparentTemperatureHigh": 97.85,
                        "apparentTemperatureHighTime": 1600781100,
                        "apparentTemperatureLow": 77.44,
                        "apparentTemperatureLowTime": 1600828260,
                        "dewPoint": 59.79,
                        "humidity": 0.42,
                        "pressure": 1009.6,
                        "windSpeed": 9.11,
                        "windGust": 21.76,
                        "windGustTime": 1600754400,
                        "windBearing": 131,
                        "cloudCover": 0.18,
                        "uvIndex": 14,
                        "uvIndexTime": 1600767240,
                        "visibility": 10,
                        "ozone": 269.4,
                        "temperatureMin": 75.56,
                        "temperatureMinTime": 1600743240,
                        "temperatureMax": 98.35,
                        "temperatureMaxTime": 1600781100,
                        "apparentTemperatureMin": 76.28,
                        "apparentTemperatureMinTime": 1600743240,
                        "apparentTemperatureMax": 97.85,
                        "apparentTemperatureMaxTime": 1600781100
                    },
                    {
                        "time": 1600808400,
                        "summary": "Rain in the morning.",
                        "icon": "rain",
                        "sunriseTime": 1600831920,
                        "sunsetTime": 1600875540,
                        "moonPhase": 0.24,
                        "precipIntensity": 0.0139,
                        "precipIntensityMax": 0.084,
                        "precipIntensityMaxTime": 1600830840,
                        "precipProbability": 0.63,
                        "precipType": "rain",
                        "temperatureHigh": 96.04,
                        "temperatureHighTime": 1600868040,
                        "temperatureLow": 75.62,
                        "temperatureLowTime": 1600914120,
                        "apparentTemperatureHigh": 95.54,
                        "apparentTemperatureHighTime": 1600868040,
                        "apparentTemperatureLow": 76.93,
                        "apparentTemperatureLowTime": 1600914180,
                        "dewPoint": 64.22,
                        "humidity": 0.51,
                        "pressure": 1009.7,
                        "windSpeed": 8.26,
                        "windGust": 18.99,
                        "windGustTime": 1600812240,
                        "windBearing": 125,
                        "cloudCover": 0.74,
                        "uvIndex": 6,
                        "uvIndexTime": 1600852320,
                        "visibility": 9.366,
                        "ozone": 268.8,
                        "temperatureMin": 75.94,
                        "temperatureMinTime": 1600827900,
                        "temperatureMax": 96.04,
                        "temperatureMaxTime": 1600868040,
                        "apparentTemperatureMin": 77.44,
                        "apparentTemperatureMinTime": 1600828260,
                        "apparentTemperatureMax": 95.54,
                        "apparentTemperatureMaxTime": 1600868040
                    }
                ]
            },
            "flags": {
                "sources": [
                    "cmc",
                    "gfs",
                    "icon",
                    "isd",
                    "madis"
                ],
                "units": "us"
            },
            "offset": 3
        }