version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-laravel
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
      - "6001:6001"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/laravel
    depends_on:
      - redis
      - mysql
    volumes:
      - ./:/var/www/laravel
      - ./docker/supervisor/:/etc/supervisor/conf.d/
    networks:
      - app-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./:/var/www/laravel
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  #MySQL Service
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
    tty: true
    ports:
      - 3306:3306
    networks:
      - app-network

  #Redis service
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
